// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC72BJr5zMEqWHEX1EgOiockUrDbF9xuj4',
    appId: '1:686761540478:web:6ce8b57b3071b30446912f',
    messagingSenderId: '686761540478',
    projectId: 'prompt-app-4c8ad',
    authDomain: 'prompt-app-4c8ad.firebaseapp.com',
    storageBucket: 'prompt-app-4c8ad.firebasestorage.app',
    measurementId: 'G-0D8MQ3YZ2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBntjM4OQMz9oFYc5RL5CeB-mYix7b85sg',
    appId: '1:686761540478:android:d0f8407452686e7746912f',
    messagingSenderId: '686761540478',
    projectId: 'prompt-app-4c8ad',
    storageBucket: 'prompt-app-4c8ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy5PoKoYVVfLPfY3vvhNgVnIBiP8WqQUs',
    appId: '1:686761540478:ios:fe6df412031adc6946912f',
    messagingSenderId: '686761540478',
    projectId: 'prompt-app-4c8ad',
    storageBucket: 'prompt-app-4c8ad.firebasestorage.app',
    iosBundleId: 'com.anilmonitor.trendybaba.ai.prompt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy5PoKoYVVfLPfY3vvhNgVnIBiP8WqQUs',
    appId: '1:686761540478:ios:fe6df412031adc6946912f',
    messagingSenderId: '686761540478',
    projectId: 'prompt-app-4c8ad',
    storageBucket: 'prompt-app-4c8ad.firebasestorage.app',
    iosBundleId: 'com.anilmonitor.trendybaba.ai.prompt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC72BJr5zMEqWHEX1EgOiockUrDbF9xuj4',
    appId: '1:686761540478:web:7a45fc84b8d9177946912f',
    messagingSenderId: '686761540478',
    projectId: 'prompt-app-4c8ad',
    authDomain: 'prompt-app-4c8ad.firebaseapp.com',
    storageBucket: 'prompt-app-4c8ad.firebasestorage.app',
    measurementId: 'G-V95XBQGYQJ',
  );
}
